#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Jan  1 02:45:59 2042
#

import wx


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((466, 570))
        self.SetTitle(u"Inicio de sesión")
        self.SetBackgroundColour(wx.Colour(33, 158, 188))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_2.Add((0, 0), 0, 0, 0)

        grid_sizer_2.Add((0, 0), 0, 0, 0)

        bmLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("CineLogo.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bmLogo, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_7.Add((0, 0), 0, 0, 0)

        bmUsuario = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Usuario.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(bmUsuario, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7.Add((0, 0), 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_5 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:")
        lbUsuario.SetForegroundColour(wx.Colour(2, 48, 71))
        lbUsuario.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_5.Add(lbUsuario, 0, wx.ALIGN_CENTER, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_5.Add(self.tfUsuario, 0, wx.ALIGN_CENTER | wx.LEFT, 0)

        grid_sizer_3 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        lbcontrasenna = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:")
        lbcontrasenna.SetForegroundColour(wx.Colour(2, 48, 71))
        lbcontrasenna.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_6.Add(lbcontrasenna, 0, wx.ALIGN_CENTER, 0)

        self.tfcontrasenna = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        grid_sizer_6.Add(self.tfcontrasenna, 0, wx.ALIGN_CENTER | wx.LEFT, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnAceptar = wx.Button(self.panel_1, wx.ID_ANY, "Aceptar")
        self.btnAceptar.SetForegroundColour(wx.Colour(2, 48, 71))
        self.btnAceptar.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(self.btnAceptar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCancelar.SetForegroundColour(wx.Colour(2, 48, 71))
        self.btnCancelar.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(self.btnCancelar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnAceptar.Bind(wx.EVT_BUTTON, self.confirma_usuario_contrasenna)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirma_usuario_contrasenna(self, event):  # wxGlade: Ventana1.<event_handler>
        
        nombre=self.tfUsuario.GetValue()
        clave=self.tfcontrasenna.GetValue()
        
        if nombre=="Falcon" and clave == "1234":
            wx.MessageBox(f"¡Bienvenid@, {nombre}! Acceso autirizado.", "Inicio de sesión", wx.OK | wx.ICON_INFORMATION)
            print(f"¡Bienvenid@, {nombre}! Acceso autirizado.")
            v2 = Ventana2(self)
            v2.Show()
            self.Hide()
        else:
            wx.MessageBox("Acceo denegado. Usuario o Clave incorrectos.", "Inicio de sesión", wx.OK | wx.ICON_ERROR)
            print("Acceo denegado. Usuario o Clave incorrectos.")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        pregunta=wx.MessageDialog(self,"Se cerrara la ventana.\n"\
                     "¿Estas seguro que deseas salir?","Confirmar salida", style = wx.YES_NO | wx.ICON_WARNING)
        respuesta =pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta==wx.ID_YES:
            print("BYe")
            self.Close()
        event.Skip()

# end of class Ventana1
class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((550, 549))
        self.SetTitle("Taquilla")

        self.subtotal = 0
        self.menores = 0
        self.adultos = 0
        self.pelicula = ""
        self.horario = ""
        self.sala = ""

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(33, 158, 188))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        lbTaquilla.SetForegroundColour(wx.Colour(255, 183, 3))
        lbTaquilla.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_2.Add(lbTaquilla, 0, wx.ALIGN_CENTER, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        grid_sizer_2.Add(label_1, 0, 0, 0)

        bmlogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./CineLogo.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bmlogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_3 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        lbPelicula.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_4.Add(lbPelicula, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.cmbPeliculas = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["La toalla del mojado 2", "En busca de la seriedad", "Interseriedad"], style=wx.CB_DROPDOWN)
        self.cmbPeliculas.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_4.Add(self.cmbPeliculas, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        lbHorario.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_5.Add(lbHorario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.cmbHorario = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.cmbHorario.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_5.Add(self.cmbHorario, 0, wx.ALIGN_RIGHT | wx.RIGHT, 0)

        grid_sizer_6 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        self.lbSala.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_6.Add(self.lbSala, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbVerSala = wx.StaticText(self.panel_1, wx.ID_ANY, ". . .")
        self.lbVerSala.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_6.Add(self.lbVerSala, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.bmpelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./pelicula1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(self.bmpelicula, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_8 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        lbAdultos1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos:")
        lbAdultos1.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_8.Add(lbAdultos1, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfAdultos.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_8.Add(self.tfAdultos, 0, 0, 0)

        lbMenores1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores:")
        lbMenores1.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_8.Add(lbMenores1, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfMenores.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_8.Add(self.tfMenores, 0, 0, 0)

        self.btnCalcular = wx.Button(self.panel_1, wx.ID_ANY, "Calcular")
        self.btnCalcular.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_7.Add(self.btnCalcular, 0, wx.ALIGN_CENTER | wx.LEFT, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_16.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_11.Add(label_16, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_12 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        lbAdultos = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos")
        lbAdultos.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_12.Add(lbAdultos, 0, wx.ALIGN_CENTER, 0)

        self.lbVerAdultos = wx.StaticText(self.panel_1, wx.ID_ANY, ". . . ")
        self.lbVerAdultos.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_12.Add(self.lbVerAdultos, 0, 0, 0)

        lbMenores = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores")
        lbMenores.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_12.Add(lbMenores, 0, wx.ALIGN_CENTER, 0)

        self.lbVerMenores = wx.StaticText(self.panel_1, wx.ID_ANY, ". . . ")
        self.lbVerMenores.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_12.Add(self.lbVerMenores, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal")
        lbSubtotal.SetForegroundColour(wx.Colour(2, 48, 71))
        lbSubtotal.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_10.Add(lbSubtotal, 0, wx.ALIGN_CENTER, 0)

        self.lbVerSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "...$")
        self.lbVerSubtotal.SetMinSize((17, 16))
        self.lbVerSubtotal.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_10.Add(self.lbVerSubtotal, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnVolver = wx.Button(self.panel_1, wx.ID_ANY, "Volver")
        self.btnVolver.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_1.Add(self.btnVolver, 0, wx.ALIGN_CENTER, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_1.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_1.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPeliculas.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.cmbHorario.Bind(wx.EVT_COMBOBOX, self.seleccionHorario)
        self.btnCalcular.Bind(wx.EVT_BUTTON, self.calcularBoletos)
        self.btnVolver.Bind(wx.EVT_BUTTON, self.volverVentana)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarVentana)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self, ruta):
        bitmap = wx.Bitmap(ruta, wx.BITMAP_TYPE_ANY)
        self.bmpelicula.SetBitmap(bitmap)
    
    def seleccionHorario(self, event):
        self.horario = self.cmbHorario.GetValue()
        print(f"Horario: {self.horario}")
        event.Skip()
    
    def seleccionPelicula(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.cmbPeliculas.GetValue()
        imagen=""
        sala=""
        self.cmbHorario.SetSelection(wx.NOT_FOUND)
        self.cmbHorario.Clear()

        if pelicula == "La toalla del mojado 2":
            imagen="pelicula1.png"
            sala="1"
            horarios=["14:00","17:00","20:00"]
            self.cmbHorario.AppendItems(horarios)
            
        elif pelicula == "En busca de la seriedad":
            imagen="pelicula2.png"
            sala="2"
            horarios=["13:30", "16:30", "19:30"]
            self.cmbHorario.AppendItems(horarios)

        elif pelicula == "Interseriedad":
            imagen="pelicula3.png"
            sala="3"
            horarios=["15:00", "18:0", "21:00"]
            self.cmbHorario.AppendItems(horarios)
        
        self.cargar_imagen(imagen)
        self.lbVerSala.SetLabel(sala)
        self.sala = sala 
        self.pelicula = pelicula

        print(f"Pelicula seleccionada: {pelicula}")
        print(f"Sala: {sala}")
        event.Skip()

    def calcularBoletos(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.adultos= int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos *90
            self.menores= int(self.tfMenores.GetValue())
            subtotal_b = self.menores *80
            self.subtotal = subtotal_a + subtotal_b
            self.lbVerAdultos.SetLabel(f"{self.adultos}")
            self.lbVerMenores.SetLabel(f"{self.menores}")
            self.lbVerSubtotal.SetLabel(f"{self.subtotal} $")
        
        except:
            wx.MessageBox("Por favor ingresa un número válido.", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def volverVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        confirmacion = wx.MessageDialog(self, "Se regresará a la ventana anterior. La información ya escrita será eliminada.\n" \
        "¿Está seguro que quiere regresar?", "Regresar a la ventana anterior", style = wx.YES_NO | wx.ICON_WARNING)

        respuesta = confirmacion.ShowModal()
        confirmacion.Destroy()

        if respuesta == wx.ID_YES:
            v1 = Ventana1(self)
            v1.Show()
            self.limpiarT()
            self.Hide()
        event.Skip()

    def limpiarT(self):
        self.subtotal = 0
        self.menores = 0
        self.adultos = 0
        self.pelicula = ""
        self.horario = ""
        self.sala = ""
        
        self.subtotal=0
        self.cargar_imagen("CineLogo.jpg")
        self.cmbPeliculas.SetSelection(wx.NOT_FOUND)
        self.cmbHorario.SetSelection(wx.NOT_FOUND)
        self.lbVerSala.SetLabel(". . .")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.lbVerSubtotal.SetLabel("...$")
        self.lbVerAdultos.SetLabel(". . . ")
        self.lbVerMenores.SetLabel(". . . ")
    
    def limpiarVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.limpiarT()
        wx.MessageBox("Se limpió correctamente la ventana.", "Limpiar ventana", style = wx.OK | wx.ICON_INFORMATION)
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        confirmacion = wx.MessageDialog(self, f"Confirmación de taquilla.¿Está seguro que desea adquirir:\n"\
                                        f"Pelicula: {self.pelicula}\n"\
                                        f"Horario: {self.horario}\n"\
                                        f"Boletos para mayores: {self.adultos}\n"\
                                        f"Boletos para menores: {self.menores}?", "Siguiente ventana", style = wx.YES_NO | wx.ICON_INFORMATION)

        respuesta = confirmacion.ShowModal()
        confirmacion.Destroy()

        if respuesta == wx.ID_YES:
            pregunta = wx.MessageDialog(self, "¿Desea adquirir productos de dulcería?", "Adquisición de productos de dulcería", style = wx.YES_NO | wx.ICON_INFORMATION)
            deseo = pregunta.ShowModal()
            pregunta.Destroy()
            
            if deseo == wx.ID_YES:
                v3 = Ventana3(self, menores = self.menores, mayores = self.adultos, subtotalT = self.subtotal, pelicula = self.pelicula, sala = self.sala, horario = self.horario)
                v3.Show()
                self.limpiarT()
                self.Hide()
            
            elif deseo == wx.ID_NO:
                v4 = Ventana4(self, menores = self.menores, mayores = self.adultos, subtotalT = self.subtotal, pelicula = self.pelicula, sala = self.sala, horario = self.horario)
                v4.Show()
                self.limpiarT()
                self.Hide()
            
        event.Skip()

# end of class Ventana2

class Ventana3(wx.Frame):
    def __init__(self, parent, menores = 0, mayores = 0, subtotalT = 0, pelicula = "", sala = "", horario= ""):
        # begin wxGlade: Ventana3.__init__
        super().__init__(parent, style = wx.DEFAULT_FRAME_STYLE)
        self.SetSize((881, 651))
        self.SetTitle("Dulceria")

        self.subtotalDulceria = 0
        self.comboB = 0
        self.comboC = 0
        self.comboF = 0
        self.palomitasCh = 0
        self.palomitasMd = 0
        self.palomitasG = 0
        self.dulces = 0
        self.refresco = ""
        self.subtotalT = subtotalT
        self.mayores = mayores
        self.menores = menores
        self.pelicula = pelicula
        self.sala = sala
        self.horario = horario

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(33, 158, 188))

        #Variables de instancia de ventana3(Dulceria)
        self.subtotalDulceria = 0

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria \n")
        label_1.SetForegroundColour(wx.Colour(255, 183, 3))
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_2.Add((0, 0), 0, 0, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("CineLogo.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_6, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_9 = wx.GridSizer(1, 4, 0, 0)
        grid_sizer_4.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        grid_sizer_10 = wx.FlexGridSizer(4, 3, 0, 0)
        grid_sizer_9.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        grid_sizer_10.Add((0, 0), 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combos")
        label_2.SetForegroundColour(wx.Colour(2, 48, 71))
        label_2.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(label_2, 0, 0, 0)

        grid_sizer_10.Add((0, 0), 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Combo1.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_10.Add(bitmap_3, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basicos $75\nPalomitas ch\nRefresco ch")
        label_3.SetForegroundColour(wx.Colour(2, 48, 71))
        label_3.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(label_3, 0, 0, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboB.SetForegroundColour(wx.Colour(2, 48, 71))
        self.spComboB.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(self.spComboB, 0, 0, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Combo2.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_10.Add(bitmap_5, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates$130\nPalomitas md\n2 refrescos md")
        label_4.SetForegroundColour(wx.Colour(2, 48, 71))
        label_4.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(label_4, 0, 0, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboC.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(self.spComboC, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Combo3.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_10.Add(bitmap_4, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar$200\nPalomitas gd\n3refrescos gd\n2dulces")
        label_15.SetForegroundColour(wx.Colour(2, 48, 71))
        label_15.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(label_15, 0, 0, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboF.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(self.spComboF, 0, 0, 0)

        grid_sizer_11 = wx.FlexGridSizer(4, 2, 0, 0)
        grid_sizer_9.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refesco")
        label_6.SetForegroundColour(wx.Colour(2, 48, 71))
        label_6.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(label_6, 0, 0, 0)

        grid_sizer_11.Add((0, 0), 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        label_7.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(label_7, 0, 0, 0)

        self.cmbTamanyo = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Chico", "Mediano", "Grande"], style=wx.CB_DROPDOWN)
        self.cmbTamanyo.SetMinSize((111, 23))
        grid_sizer_11.Add(self.cmbTamanyo, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_8.SetForegroundColour(wx.Colour(2, 48, 71))
        label_8.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(label_8, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Cola", "Manzana", "Fresa"], style=wx.CB_DROPDOWN)
        self.cmbSabor.SetMinSize((111, 23))
        grid_sizer_11.Add(self.cmbSabor, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_5.SetForegroundColour(wx.Colour(2, 48, 71))
        label_5.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(label_5, 0, 0, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCantidad.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(self.spCantidad, 0, 0, 0)

        grid_sizer_12 = wx.FlexGridSizer(4, 2, 0, 0)
        grid_sizer_9.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_10.SetForegroundColour(wx.Colour(2, 48, 71))
        label_10.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(label_10, 0, 0, 0)

        grid_sizer_12.Add((0, 0), 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        label_11.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(label_11, 0, 0, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasCh.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(self.spPalomitasCh, 0, 0, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediana")
        label_12.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(label_12, 0, 0, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasMd.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(self.spPalomitasMd, 0, wx.ALIGN_CENTER, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        label_13.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(label_13, 0, 0, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasG.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(self.spPalomitasG, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulces")
        label_14.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_13.Add(label_14, 0, 0, 0)

        self.spDulces = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spDulces.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_13.Add(self.spDulces, 0, 0, 0)

        self.btnCalcular = wx.Button(self.panel_1, wx.ID_ANY, "Calcular\n")
        self.btnCalcular.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(self.btnCalcular, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        label_16.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_3.Add(label_16, 0, wx.ALIGN_CENTER, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "..........")
        self.lbSubtotal.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_3.Add(self.lbSubtotal, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnVolver = wx.Button(self.panel_1, wx.ID_ANY, "Volver")
        self.btnVolver.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_1.Add(self.btnVolver, 0, wx.ALIGN_CENTER, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar\n")
        self.btnLimpiar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_1.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente\n")
        self.btnSiguiente.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_1.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCalcular.Bind(wx.EVT_BUTTON, self.calcular)
        self.btnVolver.Bind(wx.EVT_BUTTON, self.volverVentana)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarVentana)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def calcular(self, event):  # wxGlade: Ventana3.<event_handler>
        
        subtotalCB=subtotalCC=subtotalCF=subtotalDulces=subtotalPCh=subtotalPMd=subtotalPG=subtotalR=0

        cantidadCB = int(self.spComboB.GetValue())
        cantidadCC = int(self.spComboC.GetValue())
        cantidadCF = int(self.spComboF.GetValue())
        cantidadDulces = int(self.spDulces.GetValue())
        cantidadPCh = int(self.spPalomitasCh.GetValue())
        cantidadPMd = int(self.spPalomitasMd.GetValue())
        cantidadPG = int(self.spPalomitasG.GetValue())
        cantidadR = int(self.spCantidad.GetValue())
        seleccion = self.cmbTamanyo.GetValue()
        sabor = self.cmbSabor.GetValue()

        subtotalCB = cantidadCB * 75 
        subtotalCC = cantidadCC * 130
        subtotalCF = cantidadCF * 200
        subtotalDulces = cantidadDulces * 25
        subtotalPCh = cantidadPCh * 30
        subtotalPMd = cantidadPMd * 50
        subtotalPG = cantidadPG * 70
        
        if seleccion == "Chico":
            subtotalR = cantidadR * 25
        elif seleccion == "Mediano":
            subtotalR = cantidadR * 40
        elif seleccion == "Grande":
            subtotalR = cantidadR * 60
        
        self.subtotalDulceria = subtotalCB+subtotalCC+subtotalCF+subtotalDulces+subtotalPCh+subtotalPMd+subtotalPG+subtotalR
        self.lbSubtotal.SetLabel(f"{self.subtotalDulceria} $")

        self.comboB = cantidadCB
        self.comboC = cantidadCC
        self.comboF = cantidadCF
        self.palomitasCh = cantidadPCh
        self.palomitasMd = cantidadPMd
        self.palomitasG = cantidadPG
        self.dulces = cantidadDulces
        self.refresco = f"{cantidadR} refrescos {seleccion} sabor {sabor}"

        print(f"Combo básico: {cantidadCB}")
        print(f"Combo cuates: {cantidadCC}")
        print(f"Combo familiar: {cantidadCF}")
        print(f"Palomitas chicas: {cantidadPCh}")
        print(f"Palomitas medianas: {cantidadPMd}")
        print(f"Palomitas grandes: {cantidadPG}")
        print(f"Cantidad dulces: {cantidadDulces}")
        print(f"{self.refresco}")

        event.Skip()

    def limpiarD(self):
        self.subtotalDulceria = 0
        self.comboB = 0
        self.comboC = 0
        self.comboF = 0
        self.palomitasCh = 0
        self.palomitasMd = 0
        self.palomitasG = 0
        self.dulces = 0
        self.refresco = ""

        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spDulces.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamanyo.SetSelection(wx.NOT_FOUND)
        self.lbSubtotal.SetLabel("..........")
        
    
    def volverVentana(self, event):  # wxGlade: Ventana3.<event_handler>
        confirmacion = wx.MessageDialog(self, "Se regresará a la ventana anterior. La información ya escrita será eliminada.\n" \
        "¿Está seguro que quiere regresar?", "Regresar a la ventana anterior", style = wx.YES_NO | wx.ICON_WARNING)

        respuesta = confirmacion.ShowModal()
        confirmacion.Destroy()

        if respuesta == wx.ID_YES:
            v2 = Ventana2(self)
            v2.Show()
            self.limpiarD()
            self.Hide()
        event.Skip()

    def limpiarVentana(self, event):  # wxGlade: Ventana3.<event_handler>
        self.limpiarD()
        wx.MessageBox("Se limpió correctamente la ventana.", "Limpiar ventana", style = wx.OK | wx.ICON_INFORMATION)
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana3.<event_handler>
        confirmacion = wx.MessageDialog(self, "Confirmación de dulcería."\
        "¿Está seguro que desea adquirir\n" 
        f"Combo básico: {self.comboB}\n"
        f"Combo cuates: {self.comboC}\n"
        f"Combo familiar: {self.comboF}\n"
        f"Palomitas chicas: {self.palomitasCh}\n"
        f"Palomitas medianas: {self.palomitasMd}\n"
        f"Palomitas grandes: {self.palomitasG}\n"
        f"Cantidad dulces: {self.dulces}\n"
        f"{self.refresco}?", "Siguiente ventana", style = wx.YES_NO | wx.ICON_INFORMATION)

        respuesta = confirmacion.ShowModal()
        confirmacion.Destroy()

        if respuesta == wx.ID_YES:
            v4 = Ventana4(self, subtotalD = self.subtotalDulceria, comboB = self.comboB, comboC = self.comboC, comboF = self.comboF, palomitasCh = self.palomitasCh,\
                           palomitasMd = self.palomitasMd, palomitasG = self.palomitasG, dulces = self.dulces, refresco = self.refresco, subtotalT = self.subtotalT,\
                              mayores = self.mayores , menores = self.menores, pelicula = self.pelicula, sala = self.sala, horario = self.horario)
            v4.Show()
            self.limpiarD()
            self.Hide()
        event.Skip()

# end of class Ventana3

class Ventana4(wx.Frame):
    def __init__(self, parent, subtotalD=0, comboB=0, comboC=0, comboF=0, palomitasCh=0, palomitasMd=0, palomitasG=0, dulces=0, refresco="",\
                 subtotalT=0, mayores=0, menores=0, pelicula="", sala = "", horario=""):
        # begin wxGlade: Ventana4.__init__
        super().__init__(parent, style = wx.DEFAULT_FRAME_STYLE)
        self.SetSize((712, 737))
        self.SetTitle("Desglose de compra")

        self.subtotalD =subtotalD
        self.comboB = comboB
        self.comboC = comboC
        self.comboF = comboF
        self.palomitasCh = palomitasCh
        self.palomitasMd = palomitasMd
        self.palomitasG = palomitasG 
        self.dulces = dulces
        self.refresco = refresco
        self.subtotalT = subtotalT
        self.mayores = mayores
        self.menores = menores
        self.pelicula = pelicula 
        self.sala = sala
        self.horario = horario
        self.total = self.subtotalD + self.subtotalT


        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((200, 698))
        self.panel_1.SetBackgroundColour(wx.Colour(33, 158, 188))
        self.panel_1.SetFont(wx.Font(8, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        IbDesglosedecompra = wx.StaticText(self.panel_1, wx.ID_ANY, "Desglose de compra\n\n")
        IbDesglosedecompra.SetForegroundColour(wx.Colour(255, 183, 3))
        IbDesglosedecompra.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_1.Add(IbDesglosedecompra, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("CineLogo.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(2, 1, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        IbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        IbTaquilla.SetForegroundColour(wx.Colour(2, 48, 71))
        IbTaquilla.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_4.Add(IbTaquilla, 0, wx.ALIGN_CENTER, 0)

        IbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        IbDulceria.SetForegroundColour(wx.Colour(2, 48, 71))
        IbDulceria.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_4.Add(IbDulceria, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_7 = wx.GridSizer(5, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula")
        label_4.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(label_4, 0, 0, 0)

        self.lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.pelicula}")
        self.lbPelicula.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(self.lbPelicula, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario")
        label_5.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(label_5, 0, 0, 0)

        self.lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.horario}")
        self.lbHorario.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(self.lbHorario, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala")
        label_6.SetForegroundColour(wx.Colour(0, 0, 0))
        label_6.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(label_6, 0, 0, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.sala}")
        self.lbSala.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(self.lbSala, 0, 0, 0)

        j = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos para mayores")
        j.SetForegroundColour(wx.Colour(0, 0, 0))
        j.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_7.Add(j, 0, 0, 0)

        self.IbBoletosM = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.mayores}")
        self.IbBoletosM.SetForegroundColour(wx.Colour(2, 48, 71))
        self.IbBoletosM.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(self.IbBoletosM, 0, 0, 0)

        n = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos para menores")
        n.SetForegroundColour(wx.Colour(0, 0, 0))
        n.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(n, 0, 0, 0)

        self.lbBoletosm = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.menores}")
        self.lbBoletosm.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(self.lbBoletosm, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(4, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.lbPalomitasCh = wx.StaticText(self.panel_1, wx.ID_ANY, f"Palomitas chicas: {self.palomitasCh}")
        self.lbPalomitasCh.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(self.lbPalomitasCh, 0, 0, 0)

        self.lbComboB = wx.StaticText(self.panel_1, wx.ID_ANY, f"Combo basico:{self.comboB}")
        self.lbComboB.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(self.lbComboB, 0, 0, 0)

        self.lbPalomitasMd = wx.StaticText(self.panel_1, wx.ID_ANY, f"Palomitas medianas:{self.palomitasMd}")
        self.lbPalomitasMd.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(self.lbPalomitasMd, 0, 0, 0)

        self.lbComboC = wx.StaticText(self.panel_1, wx.ID_ANY, f"Combo cuates:{self.comboC}")
        self.lbComboC.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(self.lbComboC, 0, 0, 0)

        self.llbPalomitasG = wx.StaticText(self.panel_1, wx.ID_ANY, f"Palomitas grandes:{self.palomitasG}")
        self.llbPalomitasG.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(self.llbPalomitasG, 0, 0, 0)

        self.lbComboF = wx.StaticText(self.panel_1, wx.ID_ANY, f"Combo familiar:{self.comboF}")
        self.lbComboF.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(self.lbComboF, 0, 0, 0)

        self.lbDulces = wx.StaticText(self.panel_1, wx.ID_ANY, f"Dulces:{self.dulces}")
        self.lbDulces.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(self.lbDulces, 0, 0, 0)

        self.lbRefresco = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.refresco}")
        self.lbRefresco.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(self.lbRefresco, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 6, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        IbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Taquilla:")
        IbSubtotal.SetMinSize((111, 15))
        IbSubtotal.SetForegroundColour(wx.Colour(0, 0, 0))
        IbSubtotal.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(IbSubtotal, 0, wx.ALIGN_CENTER, 0)

        self.label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.subtotalT} $")
        self.label_1.SetForegroundColour(wx.Colour(0, 0, 0))
        self.label_1.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(self.label_1, 0, wx.ALIGN_CENTER, 0)

        IbSubtotalD = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria:")
        IbSubtotalD.SetMinSize((113, 15))
        IbSubtotalD.SetForegroundColour(wx.Colour(0, 0, 0))
        IbSubtotalD.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(IbSubtotalD, 0, wx.ALIGN_CENTER, 0)

        self.label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.subtotalD} $")
        self.label_2.SetForegroundColour(wx.Colour(0, 0, 0))
        self.label_2.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(self.label_2, 0, wx.ALIGN_CENTER, 0)

        IbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Total")
        IbTotal.SetForegroundColour(wx.Colour(0, 0, 0))
        IbTotal.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(IbTotal, 0, wx.ALIGN_CENTER, 0)

        self.label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.total} $")
        self.label_3.SetForegroundColour(wx.Colour(0, 0, 0))
        self.label_3.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(self.label_3, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_2 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_9 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        self.btnVolver = wx.Button(self.panel_1, wx.ID_ANY, "Volver")
        self.btnVolver.SetMinSize((120, 35))
        self.btnVolver.SetForegroundColour(wx.Colour(2, 48, 71))
        self.btnVolver.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_9.Add(self.btnVolver, 0, wx.ALIGN_CENTER | wx.ALL, 5)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCancelar.SetMinSize((120, 35))
        self.btnCancelar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_9.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.btnCobrar = wx.Button(self.panel_1, wx.ID_ANY, "Cobrar")
        self.btnCobrar.SetMinSize((120, 35))
        self.btnCobrar.SetForegroundColour(wx.Colour(2, 48, 71))
        self.btnCobrar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_9.Add(self.btnCobrar, 0, wx.ALIGN_CENTER | wx.ALL, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnVolver.Bind(wx.EVT_BUTTON, self.volverVentana)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnCobrar.Bind(wx.EVT_BUTTON, self.cobrarVenta)
        # end wxGlade

    def volverVentana(self, event):  # wxGlade: Ventana4.<event_handler>
        confirmacion = wx.MessageDialog(self, "Se regresará a la ventana anterior.\n" \
        "¿Está seguro que quiere regresar?", "Regresar a la ventana anterior", style = wx.YES_NO | wx.ICON_WARNING)

        respuesta = confirmacion.ShowModal()
        confirmacion.Destroy()

        if respuesta == wx.ID_YES:
            v3 = Ventana3(self, menores = self.menores, mayores = self.mayores, subtotalT = self.subtotalT, pelicula = self.pelicula, sala = self.sala, horario = self.horario)
            v3.Show()
            self.Hide()
        
        event.Skip()

    def cancelarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        pregunta=wx.MessageDialog(self,"La venta será cancelada.\n"\
                     "¿Estas seguro que deseas cancelar la venta?","Cancelar venta", style = wx.YES_NO | wx.ICON_WARNING)
        respuesta =pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta==wx.ID_YES:
            wx.Exit()
        event.Skip()

    def cobrarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        wx.MessageBox("Se cobró exitosamente venta", "Venta finalizada",wx.OK | wx.ICON_INFORMATION)
        v2 = Ventana2(self)
        v2.Show()
        self.Hide()
        event.Skip()

# end of class Ventana4


class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame2 = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame2)
        self.frame2.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
