#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sun Nov  2 08:46:30 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana4(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana4.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((712, 737))
        self.SetTitle("Desglose de compra")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(33, 158, 188))
        self.panel_1.SetFont(wx.Font(8, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        IbDesglosedecompra = wx.StaticText(self.panel_1, wx.ID_ANY, "Desglose de compra\n\n")
        IbDesglosedecompra.SetForegroundColour(wx.Colour(255, 183, 3))
        IbDesglosedecompra.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_1.Add(IbDesglosedecompra, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/CineLogo.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(2, 1, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        IbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        IbTaquilla.SetForegroundColour(wx.Colour(2, 48, 71))
        IbTaquilla.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_4.Add(IbTaquilla, 0, wx.ALIGN_CENTER, 0)

        IbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        IbDulceria.SetForegroundColour(wx.Colour(2, 48, 71))
        IbDulceria.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_4.Add(IbDulceria, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_5 = wx.FlexGridSizer(9, 6, 0, 0)
        grid_sizer_3.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        lbBoletosM = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos para mayores")
        lbBoletosM.SetForegroundColour(wx.Colour(2, 48, 71))
        lbBoletosM.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(lbBoletosM, 0, 0, 0)

        IbBoletosM = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        IbBoletosM.SetForegroundColour(wx.Colour(2, 48, 71))
        IbBoletosM.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(IbBoletosM, 0, 0, 0)

        VerComboBasico = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo basico")
        VerComboBasico.SetForegroundColour(wx.Colour(2, 48, 71))
        VerComboBasico.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerComboBasico, 0, 0, 0)

        MoverComboBasico = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        MoverComboBasico.SetForegroundColour(wx.Colour(2, 48, 71))
        MoverComboBasico.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(MoverComboBasico, 0, 0, 0)

        VerRefrescoCHM = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco chico de manzana")
        VerRefrescoCHM.SetForegroundColour(wx.Colour(2, 48, 71))
        VerRefrescoCHM.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerRefrescoCHM, 0, 0, 0)

        MoverRefrescoCHM = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverRefrescoCHM, 0, 0, 0)

        VerBoletosm = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos para menores")
        VerBoletosm.SetForegroundColour(wx.Colour(2, 48, 71))
        VerBoletosm.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerBoletosm, 0, 0, 0)

        MoverBoletosm = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        MoverBoletosm.SetForegroundColour(wx.Colour(2, 48, 71))
        MoverBoletosm.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(MoverBoletosm, 0, 0, 0)

        VerCombocuates = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo cuates")
        VerCombocuates.SetForegroundColour(wx.Colour(2, 48, 71))
        VerCombocuates.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerCombocuates, 0, 0, 0)

        Movercombocuates = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(Movercombocuates, 0, 0, 0)

        VerRefrescoMM = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco mediano de manzana")
        VerRefrescoMM.SetForegroundColour(wx.Colour(2, 48, 71))
        VerRefrescoMM.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerRefrescoMM, 0, 0, 0)

        MoverRefrescoMM = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverRefrescoMM, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        VerComboFamilia = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo familias")
        VerComboFamilia.SetForegroundColour(wx.Colour(2, 48, 71))
        VerComboFamilia.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerComboFamilia, 0, 0, 0)

        MoverComboFamilia = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverComboFamilia, 0, 0, 0)

        VerRefrescoGM = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrresco grande de manzana")
        VerRefrescoGM.SetForegroundColour(wx.Colour(2, 48, 71))
        VerRefrescoGM.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerRefrescoGM, 0, 0, 0)

        MoverRefrescoGM = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverRefrescoGM, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        VerPalomitasChicas = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas chicas")
        VerPalomitasChicas.SetForegroundColour(wx.Colour(2, 48, 71))
        VerPalomitasChicas.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerPalomitasChicas, 0, 0, 0)

        MoverPalomitaschicas = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverPalomitaschicas, 0, 0, 0)

        VerRefrescoCHC = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco chico de cola")
        VerRefrescoCHC.SetForegroundColour(wx.Colour(2, 48, 71))
        VerRefrescoCHC.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerRefrescoCHC, 0, 0, 0)

        MoverRefrescoCHC = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverRefrescoCHC, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        VerPalomitasMedianas = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas medianas")
        VerPalomitasMedianas.SetForegroundColour(wx.Colour(2, 48, 71))
        VerPalomitasMedianas.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerPalomitasMedianas, 0, 0, 0)

        MoverPalomitasmedianas = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverPalomitasmedianas, 0, 0, 0)

        VerRefrescoMC = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco mediano de cola")
        VerRefrescoMC.SetForegroundColour(wx.Colour(2, 48, 71))
        VerRefrescoMC.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerRefrescoMC, 0, 0, 0)

        MoverRefrescoMC = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverRefrescoMC, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        VerPalomitasGrandes = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas grandes")
        VerPalomitasGrandes.SetForegroundColour(wx.Colour(2, 48, 71))
        VerPalomitasGrandes.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerPalomitasGrandes, 0, 0, 0)

        MoverPalomitasGrandes = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverPalomitasGrandes, 0, 0, 0)

        VerRefrescoGC = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco grande de cola")
        VerRefrescoGC.SetForegroundColour(wx.Colour(2, 48, 71))
        VerRefrescoGC.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(VerRefrescoGC, 0, 0, 0)

        MoverRefrescoGC = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(MoverRefrescoGC, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        lbDulce = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulces")
        lbDulce.SetForegroundColour(wx.Colour(2, 48, 71))
        lbDulce.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(lbDulce, 0, 0, 0)

        lbDulces = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(lbDulces, 0, 0, 0)

        lbRefrescoCHs = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco chico de sprite")
        lbRefrescoCHs.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(lbRefrescoCHs, 0, 0, 0)

        lbRefrescoCHS = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(lbRefrescoCHS, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        lbRefrescoMs = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco mediano de sprite")
        lbRefrescoMs.SetForegroundColour(wx.Colour(2, 48, 71))
        lbRefrescoMs.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(lbRefrescoMs, 0, 0, 0)

        lbRefrescoMS = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(lbRefrescoMS, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        lbRefrescoGs = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco grande de sprite")
        lbRefrescoGs.SetForegroundColour(wx.Colour(2, 48, 71))
        lbRefrescoGs.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(lbRefrescoGs, 0, 0, 0)

        lbRefrescoGS = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_5.Add(lbRefrescoGS, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 6, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        IbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Taquilla:")
        IbSubtotal.SetForegroundColour(wx.Colour(2, 48, 71))
        IbSubtotal.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(IbSubtotal, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        label_1.SetForegroundColour(wx.Colour(2, 48, 71))
        label_1.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbSubtotalD = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria:")
        IbSubtotalD.SetForegroundColour(wx.Colour(2, 48, 71))
        IbSubtotalD.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(IbSubtotalD, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        label_2.SetForegroundColour(wx.Colour(2, 48, 71))
        label_2.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Total")
        IbTotal.SetForegroundColour(wx.Colour(2, 48, 71))
        IbTotal.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(IbTotal, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        label_3.SetForegroundColour(wx.Colour(2, 48, 71))
        label_3.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(label_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.IbVolver = wx.Button(self.panel_1, wx.ID_ANY, "Volver")
        self.IbVolver.SetMinSize((120, 35))
        self.IbVolver.SetForegroundColour(wx.Colour(2, 48, 71))
        self.IbVolver.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_2.Add(self.IbVolver, 0, wx.ALIGN_CENTER | wx.ALL, 5)

        self.IbCobrar = wx.Button(self.panel_1, wx.ID_ANY, "Cobrar")
        self.IbCobrar.SetMinSize((120, 35))
        self.IbCobrar.SetForegroundColour(wx.Colour(2, 48, 71))
        self.IbCobrar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_2.Add(self.IbCobrar, 0, wx.ALIGN_CENTER | wx.ALL, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.IbVolver.Bind(wx.EVT_BUTTON, self.confirmar_volver)
        self.IbCobrar.Bind(wx.EVT_BUTTON, self.confirmar_cobrar)
        # end wxGlade

    def confirmar_volver(self, event):  # wxGlade: Ventana4.<event_handler>
        print("Event handler 'confirmar_volver' not implemented!")
        event.Skip()

    def confirmar_cobrar(self, event):  # wxGlade: Ventana4.<event_handler>
        print("Event handler 'confirmar_cobrar' not implemented!")
        event.Skip()

# end of class Ventana4

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame = Ventana4(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
