#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sun Nov  2 08:44:44 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana3.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((881, 656))
        self.SetTitle("Dulceria")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(33, 158, 188))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria \n")
        label_1.SetForegroundColour(wx.Colour(255, 183, 3))
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_2.Add((0, 0), 0, 0, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/CineLogo.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_6, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_9 = wx.GridSizer(1, 4, 0, 0)
        grid_sizer_4.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        grid_sizer_10 = wx.FlexGridSizer(4, 3, 0, 0)
        grid_sizer_9.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        grid_sizer_10.Add((0, 0), 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combos")
        label_2.SetForegroundColour(wx.Colour(2, 48, 71))
        label_2.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(label_2, 0, 0, 0)

        grid_sizer_10.Add((0, 0), 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/Combo1.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_10.Add(bitmap_3, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basicos $75\nPalomitas ch\nRefresco ch")
        label_3.SetForegroundColour(wx.Colour(2, 48, 71))
        label_3.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(label_3, 0, 0, 0)

        self.spin_ctrl_9 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spin_ctrl_9.SetForegroundColour(wx.Colour(2, 48, 71))
        self.spin_ctrl_9.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(self.spin_ctrl_9, 0, 0, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/Combo2.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_10.Add(bitmap_5, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates$130\nPalomitas md\n2 refrescos md")
        label_4.SetForegroundColour(wx.Colour(2, 48, 71))
        label_4.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(label_4, 0, 0, 0)

        self.spin_ctrl_10 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spin_ctrl_10.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(self.spin_ctrl_10, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/Combo3.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_10.Add(bitmap_4, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar$200\nPalomitas gd\n3refrescos gd\n2dulces")
        label_15.SetForegroundColour(wx.Colour(2, 48, 71))
        label_15.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(label_15, 0, 0, 0)

        self.spin_ctrl_2 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spin_ctrl_2.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_10.Add(self.spin_ctrl_2, 0, 0, 0)

        grid_sizer_11 = wx.FlexGridSizer(4, 2, 0, 0)
        grid_sizer_9.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refesco")
        label_6.SetForegroundColour(wx.Colour(2, 48, 71))
        label_6.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(label_6, 0, 0, 0)

        grid_sizer_11.Add((0, 0), 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        label_7.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(label_7, 0, 0, 0)

        self.combo_box_1 = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_11.Add(self.combo_box_1, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_8.SetForegroundColour(wx.Colour(2, 48, 71))
        label_8.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(label_8, 0, 0, 0)

        self.combo_box_7 = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_11.Add(self.combo_box_7, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_5.SetForegroundColour(wx.Colour(2, 48, 71))
        label_5.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(label_5, 0, 0, 0)

        self.spin_ctrl_4 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spin_ctrl_4.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_11.Add(self.spin_ctrl_4, 0, 0, 0)

        grid_sizer_12 = wx.FlexGridSizer(4, 2, 0, 0)
        grid_sizer_9.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_10.SetForegroundColour(wx.Colour(2, 48, 71))
        label_10.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(label_10, 0, 0, 0)

        grid_sizer_12.Add((0, 0), 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        label_11.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(label_11, 0, 0, 0)

        self.spin_ctrl_5 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spin_ctrl_5.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(self.spin_ctrl_5, 0, 0, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediana")
        label_12.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(label_12, 0, 0, 0)

        self.spin_ctrl_1 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spin_ctrl_1.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(self.spin_ctrl_1, 0, wx.ALIGN_CENTER, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        label_13.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(label_13, 0, 0, 0)

        self.spin_ctrl_12 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spin_ctrl_12.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_12.Add(self.spin_ctrl_12, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulces")
        label_14.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_13.Add(label_14, 0, 0, 0)

        self.spin_ctrl_3 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spin_ctrl_3.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_13.Add(self.spin_ctrl_3, 0, 0, 0)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Calcular\n")
        self.button_2.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        label_16.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_3.Add(label_16, 0, wx.ALIGN_CENTER, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "..........")
        label_17.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_3.Add(label_17, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.button_3 = wx.Button(self.panel_1, wx.ID_ANY, "Volver")
        self.button_3.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_1.Add(self.button_3, 0, wx.ALIGN_CENTER, 0)

        self.button_4 = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar\n")
        self.button_4.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_1.Add(self.button_4, 0, wx.ALIGN_CENTER, 0)

        self.button_5 = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente\n")
        grid_sizer_1.Add(self.button_5, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class Ventana3

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame3 = Ventana3(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame3)
        self.frame3.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
