#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sun Nov  2 08:45:09 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((466, 570))
        self.SetTitle(u"Inicio de sesión")
        self.SetBackgroundColour(wx.Colour(33, 158, 188))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_2.Add((0, 0), 0, 0, 0)

        grid_sizer_2.Add((0, 0), 0, 0, 0)

        bmLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/CineLogo.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bmLogo, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_7.Add((0, 0), 0, 0, 0)

        bmUsuario = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/Usuario.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(bmUsuario, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7.Add((0, 0), 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_5 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:")
        lbUsuario.SetForegroundColour(wx.Colour(2, 48, 71))
        lbUsuario.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_5.Add(lbUsuario, 0, wx.ALIGN_CENTER, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        grid_sizer_5.Add(self.tfUsuario, 0, wx.ALIGN_CENTER | wx.LEFT, 0)

        grid_sizer_3 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        lbcontrasenna = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:")
        lbcontrasenna.SetForegroundColour(wx.Colour(2, 48, 71))
        lbcontrasenna.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_6.Add(lbcontrasenna, 0, wx.ALIGN_CENTER, 0)

        self.tfcontrasenna = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        grid_sizer_6.Add(self.tfcontrasenna, 0, wx.ALIGN_CENTER | wx.LEFT, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnAceptar = wx.Button(self.panel_1, wx.ID_ANY, "Aceptar")
        self.btnAceptar.SetForegroundColour(wx.Colour(2, 48, 71))
        self.btnAceptar.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(self.btnAceptar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCancelar.SetForegroundColour(wx.Colour(2, 48, 71))
        self.btnCancelar.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(self.btnCancelar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnAceptar.Bind(wx.EVT_BUTTON, self.confirma_usuario_contrasenna)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirma_usuario_contrasenna(self, event):  # wxGlade: Ventana1.<event_handler>
        print("Event handler 'confirma_usuario_contrasenna' not implemented!")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        print("Event handler 'cerrar_programa' not implemented!")
        event.Skip()

# end of class Ventana1

class MyAppCinePlusFalcon(wx.App):
    def OnInit(self):
        self.frame_1 = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_1)
        self.frame_1.Show()
        return True

# end of class MyAppCinePlusFalcon

if __name__ == "__main__":
    appCinePlusFalcon = MyAppCinePlusFalcon(0)
    appCinePlusFalcon.MainLoop()
