#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sun Nov  2 08:45:34 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((550, 553))
        self.SetTitle("Taquilla")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(33, 158, 188))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        lbTaquilla.SetForegroundColour(wx.Colour(255, 183, 3))
        lbTaquilla.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_2.Add(lbTaquilla, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_2.Add((0, 0), 0, 0, 0)

        bmLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/CineLogo.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bmLogo, 0, wx.RIGHT, 0)

        grid_sizer_3 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        lbPelicula.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_4.Add(lbPelicula, 0, 0, 0)

        self.cmbPeliculas = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["La toalla del mojado 2", "En busca de la seriedad", "Interseriedad"], style=wx.CB_DROPDOWN)
        self.cmbPeliculas.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_4.Add(self.cmbPeliculas, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        lbHorario.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_5.Add(lbHorario, 0, 0, 0)

        self.cmbHorario = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.cmbHorario.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_5.Add(self.cmbHorario, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        lbSala.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_6.Add(lbSala, 0, 0, 0)

        lbVerSala = wx.StaticText(self.panel_1, wx.ID_ANY, ". . .")
        lbVerSala.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_6.Add(lbVerSala, 0, 0, 0)

        bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:/Falcon/Imagenes proyecto/pelicula3.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bmPelicula, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_8 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        lbAdultos1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos:")
        lbAdultos1.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_8.Add(lbAdultos1, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfAdultos.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_8.Add(self.tfAdultos, 0, 0, 0)

        lbMenores1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores:")
        lbMenores1.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_8.Add(lbMenores1, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfMenores.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_8.Add(self.tfMenores, 0, 0, 0)

        self.btnCalcular = wx.Button(self.panel_1, wx.ID_ANY, "Calcular")
        self.btnCalcular.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_7.Add(self.btnCalcular, 0, wx.ALIGN_CENTER | wx.LEFT, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_16.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_11.Add(label_16, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_12 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        lbAdultos = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos")
        lbAdultos.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_12.Add(lbAdultos, 0, wx.ALIGN_CENTER, 0)

        lbVerAdultos = wx.StaticText(self.panel_1, wx.ID_ANY, ". . . ")
        lbVerAdultos.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_12.Add(lbVerAdultos, 0, 0, 0)

        lbMenores = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores")
        lbMenores.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_12.Add(lbMenores, 0, wx.ALIGN_CENTER, 0)

        lbVerMenores = wx.StaticText(self.panel_1, wx.ID_ANY, ". . . ")
        lbVerMenores.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_12.Add(lbVerMenores, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal")
        lbSubtotal.SetForegroundColour(wx.Colour(2, 48, 71))
        lbSubtotal.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_10.Add(lbSubtotal, 0, wx.ALIGN_CENTER, 0)

        lbVerSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "...$")
        lbVerSubtotal.SetMinSize((17, 16))
        lbVerSubtotal.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_10.Add(lbVerSubtotal, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnVolver = wx.Button(self.panel_1, wx.ID_ANY, "Volver")
        self.btnVolver.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_1.Add(self.btnVolver, 0, wx.ALIGN_CENTER, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_1.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetForegroundColour(wx.Colour(2, 48, 71))
        grid_sizer_1.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class Ventana2

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame2 = Ventana2(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame2)
        self.frame2.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
